version: '3'
services:
  web:
    build: .
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=127.0.0.1"
    ports:
       - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb+srv://admin:maslo1234@cluster0.5nrw8lo.mongodb.net/?retryWrites=true&w=majority

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: